### ISSUE TITLE
Cannot read property "toexecute" of undefined

### ISSUE THREAD

**Issue by antoinevastel** [xblanc33/mrs-sam#19]
error: Error finishing crawling: TypeError: Cannot read property 'toexecute' of undefined
TypeError: Cannot read property 'toexecute' of undefined
    at nightmare.end.then.res (/home/avastel/code/mrs-sam/crawler.js:117:73)

**Comment by xblanc33** [comment]
right: it should be 
this.scenarioManager and not this.ScenarioManager.

I commited the patch !

Thanks
