### ISSUE TITLE
how to reproduce the errors after a random crawl?

### ISSUE THREAD

**Issue by monperrus** [xblanc33/mrs-sam#21]
A random crawl finds errors, validates them and saves the error paths to disk.

how to reproduce the errors once stored to disk?

**Comment by xblanc33** [comment]
The file is JSON.
You can load it and ask the player to replay it.
I'll add a sample script.

**Comment by monperrus** [comment]
> I'll add a sample script.
Looking forward to it :-)

**Comment by xblanc33** [comment]
There is now playerCLI.js that input a scenario (in JSON).
The web GUI now provides access to executed scenario (download buttons)

**Comment by monperrus** [comment]
Thanks!
